# PY300 — Summary Statistics
### Official documentation: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html

Summary statistics are the **first thing you compute** when exploring a new dataset. They give you a quick sense of the data's shape, center, spread, and potential problems.

## What Are Summary Statistics?
A compact numerical description of a dataset — answering questions like:
- How many records? (`count`)
- What is the typical value? (`mean`, `median`)
- How spread out is the data? (`std`, `variance`, `range`, `IQR`)
- Are there extreme values? (`min`, `max`, percentiles)
- What is the shape of the distribution? (`skewness`, `kurtosis`)

## Approaches Covered
1. Pure Python — manual calculation
2. `statistics` module — standard library
3. NumPy — vectorized computation
4. Pandas `.describe()` — the go-to for real datasets

> **Perspective:** Summary statistics are your data's "vital signs". Just as a doctor checks pulse and temperature before diagnosis, a data analyst checks mean, median, and std before modelling. Never skip this step.

---
## Approach 1: Pure Python — From First Principles

Understanding what each statistic *actually computes* before relying on library shortcuts.

In [ ]:
## Manual summary statistics

data = [12, 15, 18, 22, 25, 28, 30, 35, 40, 100]

n = len(data)
total = sum(data)
mean = total / n

sorted_data = sorted(data)
mid = n // 2
median = (sorted_data[mid - 1] + sorted_data[mid]) / 2 if n % 2 == 0 else sorted_data[mid]

# Variance: average of squared differences from the mean
# Population variance uses n; Sample variance uses (n-1) — Bessel's correction
variance_pop = sum((x - mean) ** 2 for x in data) / n
variance_sample = sum((x - mean) ** 2 for x in data) / (n - 1)

std_pop = variance_pop ** 0.5
std_sample = variance_sample ** 0.5

data_range = max(data) - min(data)

# Interquartile Range (IQR) — range of the middle 50%
q1_idx = n // 4
q3_idx = 3 * n // 4
q1 = sorted_data[q1_idx]
q3 = sorted_data[q3_idx]
iqr = q3 - q1

print(f"Count    : {n}")
print(f"Mean     : {mean:.2f}")
print(f"Median   : {median}")
print(f"Min      : {min(data)}")
print(f"Max      : {max(data)}")
print(f"Range    : {data_range}")
print(f"Var (pop): {variance_pop:.2f}")
print(f"Var (sam): {variance_sample:.2f}")
print(f"Std (pop): {std_pop:.2f}")
print(f"Std (sam): {std_sample:.2f}")
print(f"Q1={q1}, Q3={q3}, IQR={iqr}")

# Learning Point: Sample variance divides by (n-1) instead of n.
# This is Bessel's correction — it compensates for the fact that a sample
# tends to underestimate the true population variance. Pandas and NumPy
# default to sample variance (ddof=1) for this reason.

---
## Approach 2: `statistics` Module — Standard Library

In [ ]:
## Summary stats using the statistics module

import statistics

data = [12, 15, 18, 22, 25, 28, 30, 35, 40, 100]

print(f"Mean       : {statistics.mean(data):.2f}")
print(f"Median     : {statistics.median(data)}")
print(f"Mode       : {statistics.mode(data)}")
print(f"Stdev (sam): {statistics.stdev(data):.2f}")      # Sample std (n-1)
print(f"Stdev (pop): {statistics.pstdev(data):.2f}")     # Population std (n)
print(f"Variance   : {statistics.variance(data):.2f}")

# Quantiles — divide data into equal-sized buckets
quartiles = statistics.quantiles(data, n=4)    # Q1, Q2 (median), Q3
print(f"Quartiles  : {quartiles}")

# Harmonic mean — useful for rates (speed, price-earnings ratios)
print(f"Harmonic mean: {statistics.harmonic_mean(data):.2f}")

---
## Approach 3: NumPy — Vectorized Computation

NumPy is 10–100x faster than pure Python for large arrays because it uses C-level operations on contiguous memory.

In [ ]:
## Summary stats using NumPy

import numpy as np

data = np.array([12, 15, 18, 22, 25, 28, 30, 35, 40, 100])

print(f"Count      : {data.size}")
print(f"Mean       : {np.mean(data):.2f}")
print(f"Median     : {np.median(data):.2f}")
print(f"Std (pop)  : {np.std(data):.2f}")              # Default: ddof=0 (population)
print(f"Std (sam)  : {np.std(data, ddof=1):.2f}")      # ddof=1 for sample
print(f"Var (pop)  : {np.var(data):.2f}")
print(f"Min        : {np.min(data)}")
print(f"Max        : {np.max(data)}")
print(f"Sum        : {np.sum(data)}")

# Percentiles
print(f"25th pctile: {np.percentile(data, 25):.2f}")
print(f"50th pctile: {np.percentile(data, 50):.2f}")   # Same as median
print(f"75th pctile: {np.percentile(data, 75):.2f}")
print(f"90th pctile: {np.percentile(data, 90):.2f}")

# Caution: NumPy defaults to ddof=0 (population), while Pandas defaults to
# ddof=1 (sample). This is a common source of confusion when comparing results.

---
## Approach 4: Pandas `.describe()` — The EDA Workhorse

For real datasets, Pandas gives you a complete summary in one call.

In [ ]:
## Summary stats using Pandas

import pandas as pd

# Create a sample dataset
df = pd.DataFrame({
    'age':    [25, 30, 35, 40, 45, 28, 33, 50, 22, 60],
    'salary': [30000, 45000, 55000, 60000, 80000, 40000, 52000, 95000, 28000, 120000],
    'rating': [4.2, 3.8, 4.5, 4.0, 4.8, 3.5, 4.1, 4.9, 3.2, 4.7],
    'dept':   ['IT', 'HR', 'IT', 'Finance', 'IT', 'HR', 'Finance', 'IT', 'HR', 'Finance']
})

# .describe() — summary for numeric columns
print("=== Numeric Summary ===")
print(df.describe())

print("\n=== Include All Columns (categorical too) ===")
print(df.describe(include='all'))

print("\n=== Custom Percentiles ===")
print(df.describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9]))

In [10]:
import pandas as pd

df4=pd.read_csv("..\PY200\src\excel_100_practice_workbooks.csv")
#df4
df5 = df4[:][:39]

<>:3: SyntaxWarning: invalid escape sequence '\P'
<>:3: SyntaxWarning: invalid escape sequence '\P'
C:\Users\shrip\AppData\Local\Temp\ipykernel_29608\3481693672.py:3: SyntaxWarning: invalid escape sequence '\P'
  df4=pd.read_csv("..\PY200\src\excel_100_practice_workbooks.csv")

In [11]:
df5 = df4[:][:39]
df5.tail(5)

,Match Date,Team,Opponent,Venue,Player,Grade,Minutes Played,Points Scored,Assists,Rebounds,Fouls,Ticket Sales ($),Coach,Match Result
34,16-Mar-2026,Tigers,Panthers,Central Dome,Ishaan,Grade 6,40.0,9.0,6,2,3.0,"$1,811",Coach Nina,Win
35,18-Mar-2026,Wolves,Storm,River Court,Zara,Grade 6,18.0,27.0,3,13,2.0,"$2,041",Coach Omar,Win
36,20-Mar-2026,Tigers,Storm,Sky Hall,Ryan,Grade 7,18.0,9.0,4,6,4.0,"$1,987",Coach Nina,Win
37,22-Mar-2026,Falcons,Knights,Sky Hall,Lily,Grade 7,31.0,25.0,8,4,3.0,"$4,584",Coach Maya,Win
38,24-Mar-2026,Tigers,Comets,Sky Hall,Aarav,Grade 6,29.0,19.0,1,11,4.0,"$2,185",Coach Nina,Win

In [13]:
df6 = df5.describe()

In [ ]:
df6

       Minutes Played  Points Scored      Fouls
count       39.000000      39.000000  39.000000
mean        27.282051      20.512821   2.487179
std          7.528712       8.042230   1.636295
min         18.000000       8.000000   0.000000
25%         20.000000      13.000000   1.000000
50%         25.000000      22.000000   3.000000
75%         35.000000      27.500000   4.000000
max         40.000000      33.000000   5.000000

In [ ]:
df7 = df6.T # Transposes a data frame

In [18]:
df7

                count       mean       std   min   25%   50%   75%   max
Minutes Played   39.0  27.282051  7.528712  18.0  20.0  25.0  35.0  40.0
Points Scored    39.0  20.512821  8.042230   8.0  13.0  22.0  27.5  33.0
Fouls            39.0   2.487179  1.636295   0.0   1.0   3.0   4.0   5.0

In [20]:
df7["IQR"] = df7["75%"] - df7["25%"]
df7["LF"] =  df7["25%"] - 1.5* df7["IQR"]
df7["UB"] =  df7["75%"] + 1.5* df7["IQR"]
df7

,count,mean,std,min,25%,50%,75%,max,IQR,LF,UB
Minutes Played,39.0,27.282051,7.528712,18.0,20.0,25.0,35.0,40.0,15.0,-2.50,57.50
Points Scored,39.0,20.512821,8.042230,8.0,13.0,22.0,27.5,33.0,14.5,-8.75,49.25
Fouls,39.0,2.487179,1.636295,0.0,1.0,3.0,4.0,5.0,3.0,-3.50,8.50

In [33]:
df7["Outlier"] = []
for i in df6["minute_played]:
    if i >= LF and i <= UF:
        Print("Not Outlier")
    else :
        print("outlier")
    df7["Outlier"].append(i)

SyntaxError: unterminated string literal (detected at line 2) (2867432165.py, line 2)

In [40]:
df5["min_play_out"] = df5[ (df5["Minutes Played"] > df7.loc["Minutes Played", "UB"]) |
                                (df5["Minutes Played"] < df7.loc["Minutes Played", "LF"])].astype(int)

ValueError: Columns must be same length as key

In [35]:
df5["Min_play_out"] =  1
df5

,Match Date,Team,Opponent,Venue,Player,Grade,Minutes Played,Points Scored,Assists,Rebounds,Fouls,Ticket Sales ($),Coach,Match Result,Min_play_out
0,07-Jan-2026,Falcons,Comets,River Court,Zara,Grade 6,22.0,29.0,1,3,4.0,"$2,628",Coach Maya,Win,1
1,09-Jan-2026,Falcons,Comets,Central Dome,Zara,Grade 5,35.0,12.0,11,14,1.0,"$2,739",Coach Maya,Loss,1
2,11-Jan-2026,Falcons,Rockets,Sky Hall,Lily,Grade 7,22.0,12.0,5,4,0.0,"$2,456",Coach Maya,Win,1
3,13-Jan-2026,Tigers,Storm,River Court,Aarav,Grade 8,35.0,9.0,6,3,4.0,"$2,100",Coach Nina,Loss,1
4,15-Jan-2026,Sharks,Comets,North Arena,Ryan,Grade 6,27.0,8.0,3,4,3.0,"$2,038",Coach Leo,Loss,1
5,17-Jan-2026,Tigers,Rockets,River Court,Lily,Grade 6,39.0,14.0,11,3,4.0,"$3,500",Coach Nina,Win,1
6,19-Jan-2026,Sharks,Rockets,Sky Hall,Ethan,Grade 7,38.0,28.0,8,8,5.0,"$2,228",Coach Leo,Win,1
7,21-Jan-2026,Sharks,Comets,River Court,Ethan,Grade 7,20.0,12.0,9,11,1.0,"$3,584",Coach Leo,Loss,1
8,23-Jan-2026,Wolves,Panthers,Central Dome,Ishaan,Grade 6,25.0,29.0,8,9,5.0,"$3,294",Coach Omar,Loss,1
9,25-Jan-2026,Wolves,Storm,Central Dome,Noah,Grade 8,20.0,30.0,0,4,1.0,"$3,470",Coach Omar,Win,1
10,27-Jan-2026,Wolves,Knights,North Arena,Ethan,Grade 8,37.0,20.0,8,9,4.0,"$4,425",Coach Omar,Win,1
11,29-Jan-2026,Falcons,Knights,River Court,Ryan,Grade 7,21.0,15.0,6,6,3.0,$913,Coach Maya,Loss,1
12,31-Jan-2026,Sharks,Knights,North Arena,Ryan,Grade 7,38.0,22.0,9,7,1.0,"$2,431",Coach Leo,Win,1
13,02-Feb-2026,Falcons,Knights,River Court,Ava,Grade 5,21.0,17.0,4,8,0.0,"$1,886",Coach Maya,Win,1
14,04-Feb-2026,Falcons,Panthers,North Arena,Kabir,Grade 6,22.0,27.0,7,6,2.0,"$3,061",Coach Maya,Loss,1
15,06-Feb-2026,Sharks,Knights,Central Dome,Anaya,Grade 7,30.0,27.0,10,12,3.0,"$4,584",Coach Leo,Loss,1
16,08-Feb-2026,Falcons,Rockets,Central Dome,Mia,Grade 7,18.0,24.0,8,8,4.0,"$1,802",Coach Maya,Win,1
17,10-Feb-2026,Falcons,Comets,Central Dome,Mia,Grade 5,28.0,8.0,8,8,2.0,"$3,640",Coach Maya,Loss,1
18,12-Feb-2026,Sharks,Knights,Central Dome,Anaya,Grade 8,25.0,31.0,7,14,1.0,"$1,286",Coach Leo,Win,1
19,14-Feb-2026,Wolves,Storm,Sky Hall,Ethan,Grade 8,19.0,27.0,10,4,0.0,"$2,549",Coach Omar,Loss,1
20,16-Feb-2026,Falcons,Rockets,Central Dome,Zara,Grade 8,22.0,19.0,2,9,3.0,"$1,923",Coach Maya,Win,1
21,18-Feb-2026,Wolves,Knights,North Arena,Aarav,Grade 5,20.0,30.0,3,6,3.0,"$2,889",Coach Omar,Loss,1
22,20-Feb-2026,Sharks,Panthers,North Arena,Noah,Grade 8,18.0,18.0,4,15,2.0,"$2,632",Coach Leo,Loss,1
23,22-Feb-2026,Sharks,Rockets,River Court,Zara,Grade 5,36.0,29.0,8,2,5.0,"$2,184",Coach Leo,Win,1
24,24-Feb-2026,Falcons,Knights,Sky Hall,Kabir,Grade 6,19.0,22.0,1,6,0.0,"$3,337",Coach Maya,Win,1
25,26-Feb-2026,Sharks,Panthers,North Arena,Sofia,Grade 6,36.0,25.0,0,3,3.0,"$3,592",Coach Leo,Loss,1
26,28-Feb-2026,Tigers,Rockets,River Court,Zara,Grade 7,30.0,10.0,10,10,3.0,"$2,195",Coach Nina,Win,1
27,02-Mar-2026,Falcons,Panthers,North Arena,Mia,Grade 6,34.0,14.0,2,12,0.0,"$4,501",Coach Maya,Win,1
28,04-Mar-2026,Tigers,Storm,Central Dome,Ava,Grade 7,37.0,31.0,10,1,5.0,"$4,246",Coach Nina,Loss,1
29,06-Mar-2026,Falcons,Rockets,River Court,Mia,Grade 5,35.0,10.0,4,10,4.0,"$1,762",Coach Maya,Loss,1
30,08-Mar-2026,Sharks,Storm,Sky Hall,Ishaan,Grade 5,20.0,26.0,6,9,0.0,$914,Coach Leo,Loss,1
31,10-Mar-2026,Sharks,Storm,Central Dome,Anaya,Grade 8,35.0,28.0,6,1,0.0,"$1,208",Coach Leo,Win,1
32,12-Mar-2026,Falcons,Storm,Central Dome,Ethan,Grade 6,19.0,15.0,5,2,2.0,"$1,760",Coach Maya,Win,1
33,14-Mar-2026,Falcons,Storm,Sky Hall,Sofia,Grade 6,25.0,33.0,2,6,3.0,"$1,001",Coach Maya,Win,1
34,16-Mar-2026,Tigers,Panthers,Central Dome,Ishaan,Grade 6,40.0,9.0,6,2,3.0,"$1,811",Coach Nina,Win,1
35,18-Mar-2026,Wolves,Storm,River Court,Zara,Grade 6,18.0,27.0,3,13,2.0,"$2,041",Coach Omar,Win,1
36,20-Mar-2026,Tigers,Storm,Sky Hall,Ryan,Grade 7,18.0,9.0,4,6,4.0,"$1,987",Coach Nina,Win,1
37,22-Mar-2026,Falcons,Knights,Sky Hall,Lily,Grade 7,31.0,25.0,8,4,3.0,"$4,584",Coach Maya,Win,1
38,24-Mar-2026,Tigers,Comets,Sky Hall,Aarav,Grade 6,29.0,19.0,1,11,4.0,"$2,185",Coach Nina,Win,1

In [37]:
#"Pass" if score >= 60 else "Fail"
df5["min_play_out"] = (
    (df5["Minutes Played"] > df7.loc["Minutes Played", "UB"]) |
    (df5["Minutes Played"] < df7.loc["Minutes Played", "LF"])
)

In [24]:
outliers = df5[

    (df5["Minutes Played"] > df7.loc["Minutes Played", "UB"]) |

    (df5["Minutes Played"] < df7.loc["Minutes Played", "LB"])

]
 
print(outliers)

KeyError: 'LB'

In [ ]:
## Individual Pandas stat methods

print(f"Mean salary    : {df['salary'].mean():,.2f}")
print(f"Median salary  : {df['salary'].median():,.2f}")
print(f"Std salary     : {df['salary'].std():,.2f}")     # ddof=1 by default
print(f"Skewness       : {df['salary'].skew():.2f}")     # >0 = right-skewed
print(f"Kurtosis       : {df['salary'].kurtosis():.2f}") # >0 = heavy tails

# Group-level summary
print("\n=== Salary Stats by Department ===")
print(df.groupby('dept')['salary'].describe())

# Correlation matrix — how strongly are numeric columns related?
print("\n=== Correlation Matrix ===")
print(df[['age', 'salary', 'rating']].corr().round(2))

---
## Skewness and Kurtosis — Shape of the Distribution

| Measure | What It Tells You | Value Interpretation |
|---|---|---|
| **Skewness** | Symmetry of the distribution | 0 = symmetric, >0 = right tail, <0 = left tail |
| **Kurtosis** | Heaviness of the tails | 0 = normal-like, >0 = heavy tails (outliers), <0 = light tails |

> **When to care:** Skewness > 1 or < -1 often means the mean is misleading — use the median instead. High kurtosis warns you that outliers are likely.

---
## Quick Reference

| Statistic | Pure Python | `statistics` | NumPy | Pandas |
|---|---|---|---|---|
| Mean | `sum(d)/len(d)` | `mean(d)` | `np.mean(d)` | `df.mean()` |
| Median | manual sort | `median(d)` | `np.median(d)` | `df.median()` |
| Std (sample) | manual | `stdev(d)` | `np.std(d, ddof=1)` | `df.std()` |
| Variance | manual | `variance(d)` | `np.var(d, ddof=1)` | `df.var()` |
| Percentile | manual | `quantiles(d)` | `np.percentile(d, q)` | `df.quantile(q)` |
| Full summary | — | — | — | `df.describe()` |

> **Best Practice:** Start every EDA with `df.describe()` + `df.info()` + `df.isnull().sum()`. These three calls tell you the shape, types, stats, and data quality in under 5 seconds.