## Panda
## complex data structure to mimic relational table in python

In [5]:
## installion
## import

import pandas as pd

In [4]:
list1 =[10,80,30.8,40,50,60,70]
print(type(list1))

s=pd.Series(list1)

print(type(s))
print(s)

<class 'list'>
<class 'pandas.Series'>
0    10.0
1    80.0
2    30.8
3    40.0
4    50.0
5    60.0
6    70.0
dtype: float64

In [6]:
## Series vs Dataframe

s2 =pd.Series(["Math", "sc", "ssc", "art","music","eng", "hindi"])
print(type(s2))
print(s2)

<class 'pandas.Series'>
0     Math
1       sc
2      ssc
3      art
4    music
5      eng
6    hindi
dtype: str

In [14]:
df1 = pd.DataFrame([s,s2])

In [18]:
data =[s,s2]
data

[0    10.0
 1    80.0
 2    30.8
 3    40.0
 4    50.0
 5    60.0
 6    70.0
 dtype: float64,
 0     Math
 1       sc
 2      ssc
 3      art
 4    music
 5      eng
 6    hindi
 dtype: str]

In [20]:
df2 = pd.DataFrame(data)
df2

      0     1     2     3      4     5      6
0  10.0  80.0  30.8  40.0   50.0  60.0   70.0
1  Math    sc   ssc   art  music   eng  hindi

In [15]:
print(type(df1))
print(df1)

<class 'pandas.DataFrame'>
      0     1     2     3      4     5      6
0  10.0  80.0  30.8  40.0   50.0  60.0   70.0
1  Math    sc   ssc   art  music   eng  hindi

In [49]:
df1 = pd.DataFrame(s,columns=["Subject1","Subject2","Subject3","Subject4","Subject5","Subject6","Subject7",])

ValueError: Shape of passed values is (7, 1), indices imply (7, 7)

In [48]:
d1 = { ["Math" : 10],
      ["sc" :20],
      ["ssc":30],
      ["arts":40],
      ["music":50],
       ["eng": 70],
      [ "hindi":90]

}
d1

SyntaxError: invalid syntax (717732107.py, line 1)

In [27]:
df1 =pd.DataFrame(d1)
df1

ValueError: If using all scalar values, you must pass an index

In [37]:
data =[
    [ "07-Jan-2026",	"Falcons",	"Comets",	"River Court"	," Zara",	"Grade", 6,	22,	29,	1	,3	,4,	2628,	"Coach Maya",	"Win"],
     [ "09-Jan-2026",	"Falcons",  "Comets",	"Central Dome",	"Zara",	"Grade", 5	,35,	12,	11,	14,	1,	2739,	"Coach Maya",	"Loss"]
]

df3 = pd.DataFrame(data,columns=['Match_Date','Team',	'Opponent',	'Venue',	'Player',	'Grade',	
                                 'Minutes_Played',	'Points_Scored',	'Assists',	'Rebounds',	'Fouls',	'Ticket_Sales',	'Coach',	'Match_Result',"extra"])
df3

,Match_Date,Team,Opponent,Venue,Player,Grade,Minutes_Played,Points_Scored,Assists,Rebounds,Fouls,Ticket_Sales,Coach,Match_Result,extra
0,07-Jan-2026,Falcons,Comets,River Court,Zara,Grade,6,22,29,1,3,4,2628,Coach Maya,Win
1,09-Jan-2026,Falcons,Comets,Central Dome,Zara,Grade,5,35,12,11,14,1,2739,Coach Maya,Loss

In [33]:
df3[:][0]

0    07-Jan-2026
1    09-Jan-2026
Name: 0, dtype: str

In [9]:
df4=pd.read_csv("./src/excel_100_practice_workbooks.csv")
df4

,Match Date,Team,Opponent,Venue,Player,Grade,Minutes Played,Points Scored,Assists,Rebounds,Fouls,Ticket Sales ($),Coach,Match Result
0,07-Jan-2026,Falcons,Comets,River Court,Zara,Grade 6,22.0,29.0,1,3,4.0,"$2,628",Coach Maya,Win
1,09-Jan-2026,Falcons,Comets,Central Dome,Zara,Grade 5,35.0,12.0,11,14,1.0,"$2,739",Coach Maya,Loss
2,11-Jan-2026,Falcons,Rockets,Sky Hall,Lily,Grade 7,22.0,12.0,5,4,0.0,"$2,456",Coach Maya,Win
3,13-Jan-2026,Tigers,Storm,River Court,Aarav,Grade 8,35.0,9.0,6,3,4.0,"$2,100",Coach Nina,Loss
4,15-Jan-2026,Sharks,Comets,North Arena,Ryan,Grade 6,27.0,8.0,3,4,3.0,"$2,038",Coach Leo,Loss
5,17-Jan-2026,Tigers,Rockets,River Court,Lily,Grade 6,39.0,14.0,11,3,4.0,"$3,500",Coach Nina,Win
6,19-Jan-2026,Sharks,Rockets,Sky Hall,Ethan,Grade 7,38.0,28.0,8,8,5.0,"$2,228",Coach Leo,Win
7,21-Jan-2026,Sharks,Comets,River Court,Ethan,Grade 7,20.0,12.0,9,11,1.0,"$3,584",Coach Leo,Loss
8,23-Jan-2026,Wolves,Panthers,Central Dome,Ishaan,Grade 6,25.0,29.0,8,9,5.0,"$3,294",Coach Omar,Loss
9,25-Jan-2026,Wolves,Storm,Central Dome,Noah,Grade 8,20.0,30.0,0,4,1.0,"$3,470",Coach Omar,Win
10,27-Jan-2026,Wolves,Knights,North Arena,Ethan,Grade 8,37.0,20.0,8,9,4.0,"$4,425",Coach Omar,Win
11,29-Jan-2026,Falcons,Knights,River Court,Ryan,Grade 7,21.0,15.0,6,6,3.0,$913,Coach Maya,Loss
12,31-Jan-2026,Sharks,Knights,North Arena,Ryan,Grade 7,38.0,22.0,9,7,1.0,"$2,431",Coach Leo,Win
13,02-Feb-2026,Falcons,Knights,River Court,Ava,Grade 5,21.0,17.0,4,8,0.0,"$1,886",Coach Maya,Win
14,04-Feb-2026,Falcons,Panthers,North Arena,Kabir,Grade 6,22.0,27.0,7,6,2.0,"$3,061",Coach Maya,Loss
15,06-Feb-2026,Sharks,Knights,Central Dome,Anaya,Grade 7,30.0,27.0,10,12,3.0,"$4,584",Coach Leo,Loss
16,08-Feb-2026,Falcons,Rockets,Central Dome,Mia,Grade 7,18.0,24.0,8,8,4.0,"$1,802",Coach Maya,Win
17,10-Feb-2026,Falcons,Comets,Central Dome,Mia,Grade 5,28.0,8.0,8,8,2.0,"$3,640",Coach Maya,Loss
18,12-Feb-2026,Sharks,Knights,Central Dome,Anaya,Grade 8,25.0,31.0,7,14,1.0,"$1,286",Coach Leo,Win
19,14-Feb-2026,Wolves,Storm,Sky Hall,Ethan,Grade 8,19.0,27.0,10,4,0.0,"$2,549",Coach Omar,Loss
20,16-Feb-2026,Falcons,Rockets,Central Dome,Zara,Grade 8,22.0,19.0,2,9,3.0,"$1,923",Coach Maya,Win
21,18-Feb-2026,Wolves,Knights,North Arena,Aarav,Grade 5,20.0,30.0,3,6,3.0,"$2,889",Coach Omar,Loss
22,20-Feb-2026,Sharks,Panthers,North Arena,Noah,Grade 8,18.0,18.0,4,15,2.0,"$2,632",Coach Leo,Loss
23,22-Feb-2026,Sharks,Rockets,River Court,Zara,Grade 5,36.0,29.0,8,2,5.0,"$2,184",Coach Leo,Win
24,24-Feb-2026,Falcons,Knights,Sky Hall,Kabir,Grade 6,19.0,22.0,1,6,0.0,"$3,337",Coach Maya,Win
25,26-Feb-2026,Sharks,Panthers,North Arena,Sofia,Grade 6,36.0,25.0,0,3,3.0,"$3,592",Coach Leo,Loss
26,28-Feb-2026,Tigers,Rockets,River Court,Zara,Grade 7,30.0,10.0,10,10,3.0,"$2,195",Coach Nina,Win
27,02-Mar-2026,Falcons,Panthers,North Arena,Mia,Grade 6,34.0,14.0,2,12,0.0,"$4,501",Coach Maya,Win
28,04-Mar-2026,Tigers,Storm,Central Dome,Ava,Grade 7,37.0,31.0,10,1,5.0,"$4,246",Coach Nina,Loss
29,06-Mar-2026,Falcons,Rockets,River Court,Mia,Grade 5,35.0,10.0,4,10,4.0,"$1,762",Coach Maya,Loss
30,08-Mar-2026,Sharks,Storm,Sky Hall,Ishaan,Grade 5,20.0,26.0,6,9,0.0,$914,Coach Leo,Loss
31,10-Mar-2026,Sharks,Storm,Central Dome,Anaya,Grade 8,35.0,28.0,6,1,0.0,"$1,208",Coach Leo,Win
32,12-Mar-2026,Falcons,Storm,Central Dome,Ethan,Grade 6,19.0,15.0,5,2,2.0,"$1,760",Coach Maya,Win
33,14-Mar-2026,Falcons,Storm,Sky Hall,Sofia,Grade 6,25.0,33.0,2,6,3.0,"$1,001",Coach Maya,Win
34,16-Mar-2026,Tigers,Panthers,Central Dome,Ishaan,Grade 6,40.0,9.0,6,2,3.0,"$1,811",Coach Nina,Win
35,18-Mar-2026,Wolves,Storm,River Court,Zara,Grade 6,18.0,27.0,3,13,2.0,"$2,041",Coach Omar,Win
36,20-Mar-2026,Tigers,Storm,Sky Hall,Ryan,Grade 7,18.0,9.0,4,6,4.0,"$1,987",Coach Nina,Win
37,22-Mar-2026,Falcons,Knights,Sky Hall,Lily,Grade 7,31.0,25.0,8,4,3.0,"$4,584",Coach Maya,Win
38,24-Mar-2026,Tigers,Comets,Sky Hall,Aarav,Grade 6,29.0,19.0,1,11,4.0,"$2,185",Coach Nina,Win
39,26-Mar-2026,Tigers,Knights,River Court,Ryan,Grade 8,28.0,18.0,11,10,4.0,"$1,421",Coach Nina,Win
40,NaN,NaN,NaN,for loop from 1 to 14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,14,41,574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PT,14 attributes,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,2Dlist,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df4=pd.read_csv(".\src\excel_100_practice_workbooks.csv")
df4

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\shrip\AppData\Local\Temp\ipykernel_32968\2226792748.py:1: SyntaxWarning: invalid escape sequence '\s'
  df4=pd.read_csv(".\src\excel_100_practice_workbooks.csv")
C:\Users\shrip\AppData\Local\Temp\ipykernel_32968\2226792748.py:1: SyntaxWarning: invalid escape sequence '\s'
  df4=pd.read_csv(".\src\excel_100_practice_workbooks.csv")

NameError: name 'pd' is not defined

In [ ]:
df6,df7 = pd.read_excel("file_name.xlsx",sheet_name=["sheet1","sheet2"])

In [4]:
df4=pd.read_csv(".\src\excel_100_practice_workbooks.csv")
df4

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\shrip\AppData\Local\Temp\ipykernel_32968\2226792748.py:1: SyntaxWarning: invalid escape sequence '\s'
  df4=pd.read_csv(".\src\excel_100_practice_workbooks.csv")

NameError: name 'pd' is not defined

In [50]:
data = {
    'Subject' : ['maths','english','science','sst'],
    'Marks' : [30,40,50,60]

}

df3 = pd.DataFrame(data)
print(df3)

   Subject  Marks
0    maths     30
1  english     40
2  science     50
3      sst     60

In [10]:
df4.head(3)

,Match Date,Team,Opponent,Venue,Player,Grade,Minutes Played,Points Scored,Assists,Rebounds,Fouls,Ticket Sales ($),Coach,Match Result
0,07-Jan-2026,Falcons,Comets,River Court,Zara,Grade 6,22.0,29.0,1,3,4.0,"$2,628",Coach Maya,Win
1,09-Jan-2026,Falcons,Comets,Central Dome,Zara,Grade 5,35.0,12.0,11,14,1.0,"$2,739",Coach Maya,Loss
2,11-Jan-2026,Falcons,Rockets,Sky Hall,Lily,Grade 7,22.0,12.0,5,4,0.0,"$2,456",Coach Maya,Win

In [16]:
df4.columns

Index(['Match Date', 'Team', 'Opponent', 'Venue', 'Player', 'Grade',
       'Minutes Played', 'Points Scored', 'Assists', 'Rebounds', 'Fouls',
       'Ticket Sales ($)', 'Coach', 'Match Result'],
      dtype='str')

In [17]:
df4["Points Scored"]

0     29.0
1     12.0
2     12.0
3      9.0
4      8.0
5     14.0
6     28.0
7     12.0
8     29.0
9     30.0
10    20.0
11    15.0
12    22.0
13    17.0
14    27.0
15    27.0
16    24.0
17     8.0
18    31.0
19    27.0
20    19.0
21    30.0
22    18.0
23    29.0
24    22.0
25    25.0
26    10.0
27    14.0
28    31.0
29    10.0
30    26.0
31    28.0
32    15.0
33    33.0
34     9.0
35    27.0
36     9.0
37    25.0
38    19.0
39    18.0
40     NaN
41     NaN
42     NaN
43     NaN
Name: Points Scored, dtype: float64

In [23]:
df4[6][:]

KeyError: 6

In [14]:
df4[df4.columns[6]]

0     22.0
1     35.0
2     22.0
3     35.0
4     27.0
5     39.0
6     38.0
7     20.0
8     25.0
9     20.0
10    37.0
11    21.0
12    38.0
13    21.0
14    22.0
15    30.0
16    18.0
17    28.0
18    25.0
19    19.0
20    22.0
21    20.0
22    18.0
23    36.0
24    19.0
25    36.0
26    30.0
27    34.0
28    37.0
29    35.0
30    20.0
31    35.0
32    19.0
33    25.0
34    40.0
35    18.0
36    18.0
37    31.0
38    29.0
39    28.0
40     NaN
41     NaN
42     NaN
43     NaN
Name: Minutes Played, dtype: float64

In [22]:
## Summary stats using NumPy

import numpy as np

data = np.array(df4[df4.columns[6]][:39])

print(f"Count      : {data.size}")
print(f"Mean       : {np.mean(data):.2f}")
print(f"Median     : {np.median(data):.2f}")
print(f"Std (pop)  : {np.std(data):.2f}")              # Default: ddof=0 (population)
print(f"Std (sam)  : {np.std(data, ddof=1):.2f}")      # ddof=1 for sample
print(f"Var (pop)  : {np.var(data):.2f}")
print(f"Min        : {np.min(data)}")
print(f"Max        : {np.max(data)}")
print(f"Sum        : {np.sum(data)}")

# Percentiles
print(f"25th pctile: {np.percentile(data, 25):.2f}")
print(f"50th pctile: {np.percentile(data, 50):.2f}")   # Same as median
print(f"75th pctile: {np.percentile(data, 75):.2f}")
print(f"90th pctile: {np.percentile(data, 90):.2f}")

Count      : 39
Mean       : 27.28
Median     : 25.00
Std (pop)  : 7.43
Std (sam)  : 7.53
Var (pop)  : 55.23
Min        : 18.0
Max        : 40.0
Sum        : 1064.0
25th pctile: 20.00
50th pctile: 25.00
75th pctile: 35.00
90th pctile: 37.20

In [52]:
df4.tail(5)

,Match Date,Team,Opponent,Venue,Player,Grade,Minutes Played,Points Scored,Assists,Rebounds,Fouls,Ticket Sales ($),Coach,Match Result
39,26-Mar-2026,Tigers,Knights,River Court,Ryan,Grade 8,28.0,18.0,11,10,4.0,"$1,421",Coach Nina,Win
40,NaN,NaN,NaN,for loop from 1 to 14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,14,41,574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PT,14 attributes,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,2Dlist,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
df5 =df4[:40][:]
df5

,Match Date,Team,Opponent,Venue,Player,Grade,Minutes Played,Points Scored,Assists,Rebounds,Fouls,Ticket Sales ($),Coach,Match Result
0,07-Jan-2026,Falcons,Comets,River Court,Zara,Grade 6,22.0,29.0,1,3,4.0,"$2,628",Coach Maya,Win
1,09-Jan-2026,Falcons,Comets,Central Dome,Zara,Grade 5,35.0,12.0,11,14,1.0,"$2,739",Coach Maya,Loss
2,11-Jan-2026,Falcons,Rockets,Sky Hall,Lily,Grade 7,22.0,12.0,5,4,0.0,"$2,456",Coach Maya,Win
3,13-Jan-2026,Tigers,Storm,River Court,Aarav,Grade 8,35.0,9.0,6,3,4.0,"$2,100",Coach Nina,Loss
4,15-Jan-2026,Sharks,Comets,North Arena,Ryan,Grade 6,27.0,8.0,3,4,3.0,"$2,038",Coach Leo,Loss
5,17-Jan-2026,Tigers,Rockets,River Court,Lily,Grade 6,39.0,14.0,11,3,4.0,"$3,500",Coach Nina,Win
6,19-Jan-2026,Sharks,Rockets,Sky Hall,Ethan,Grade 7,38.0,28.0,8,8,5.0,"$2,228",Coach Leo,Win
7,21-Jan-2026,Sharks,Comets,River Court,Ethan,Grade 7,20.0,12.0,9,11,1.0,"$3,584",Coach Leo,Loss
8,23-Jan-2026,Wolves,Panthers,Central Dome,Ishaan,Grade 6,25.0,29.0,8,9,5.0,"$3,294",Coach Omar,Loss
9,25-Jan-2026,Wolves,Storm,Central Dome,Noah,Grade 8,20.0,30.0,0,4,1.0,"$3,470",Coach Omar,Win
10,27-Jan-2026,Wolves,Knights,North Arena,Ethan,Grade 8,37.0,20.0,8,9,4.0,"$4,425",Coach Omar,Win
11,29-Jan-2026,Falcons,Knights,River Court,Ryan,Grade 7,21.0,15.0,6,6,3.0,$913,Coach Maya,Loss
12,31-Jan-2026,Sharks,Knights,North Arena,Ryan,Grade 7,38.0,22.0,9,7,1.0,"$2,431",Coach Leo,Win
13,02-Feb-2026,Falcons,Knights,River Court,Ava,Grade 5,21.0,17.0,4,8,0.0,"$1,886",Coach Maya,Win
14,04-Feb-2026,Falcons,Panthers,North Arena,Kabir,Grade 6,22.0,27.0,7,6,2.0,"$3,061",Coach Maya,Loss
15,06-Feb-2026,Sharks,Knights,Central Dome,Anaya,Grade 7,30.0,27.0,10,12,3.0,"$4,584",Coach Leo,Loss
16,08-Feb-2026,Falcons,Rockets,Central Dome,Mia,Grade 7,18.0,24.0,8,8,4.0,"$1,802",Coach Maya,Win
17,10-Feb-2026,Falcons,Comets,Central Dome,Mia,Grade 5,28.0,8.0,8,8,2.0,"$3,640",Coach Maya,Loss
18,12-Feb-2026,Sharks,Knights,Central Dome,Anaya,Grade 8,25.0,31.0,7,14,1.0,"$1,286",Coach Leo,Win
19,14-Feb-2026,Wolves,Storm,Sky Hall,Ethan,Grade 8,19.0,27.0,10,4,0.0,"$2,549",Coach Omar,Loss
20,16-Feb-2026,Falcons,Rockets,Central Dome,Zara,Grade 8,22.0,19.0,2,9,3.0,"$1,923",Coach Maya,Win
21,18-Feb-2026,Wolves,Knights,North Arena,Aarav,Grade 5,20.0,30.0,3,6,3.0,"$2,889",Coach Omar,Loss
22,20-Feb-2026,Sharks,Panthers,North Arena,Noah,Grade 8,18.0,18.0,4,15,2.0,"$2,632",Coach Leo,Loss
23,22-Feb-2026,Sharks,Rockets,River Court,Zara,Grade 5,36.0,29.0,8,2,5.0,"$2,184",Coach Leo,Win
24,24-Feb-2026,Falcons,Knights,Sky Hall,Kabir,Grade 6,19.0,22.0,1,6,0.0,"$3,337",Coach Maya,Win
25,26-Feb-2026,Sharks,Panthers,North Arena,Sofia,Grade 6,36.0,25.0,0,3,3.0,"$3,592",Coach Leo,Loss
26,28-Feb-2026,Tigers,Rockets,River Court,Zara,Grade 7,30.0,10.0,10,10,3.0,"$2,195",Coach Nina,Win
27,02-Mar-2026,Falcons,Panthers,North Arena,Mia,Grade 6,34.0,14.0,2,12,0.0,"$4,501",Coach Maya,Win
28,04-Mar-2026,Tigers,Storm,Central Dome,Ava,Grade 7,37.0,31.0,10,1,5.0,"$4,246",Coach Nina,Loss
29,06-Mar-2026,Falcons,Rockets,River Court,Mia,Grade 5,35.0,10.0,4,10,4.0,"$1,762",Coach Maya,Loss
30,08-Mar-2026,Sharks,Storm,Sky Hall,Ishaan,Grade 5,20.0,26.0,6,9,0.0,$914,Coach Leo,Loss
31,10-Mar-2026,Sharks,Storm,Central Dome,Anaya,Grade 8,35.0,28.0,6,1,0.0,"$1,208",Coach Leo,Win
32,12-Mar-2026,Falcons,Storm,Central Dome,Ethan,Grade 6,19.0,15.0,5,2,2.0,"$1,760",Coach Maya,Win
33,14-Mar-2026,Falcons,Storm,Sky Hall,Sofia,Grade 6,25.0,33.0,2,6,3.0,"$1,001",Coach Maya,Win
34,16-Mar-2026,Tigers,Panthers,Central Dome,Ishaan,Grade 6,40.0,9.0,6,2,3.0,"$1,811",Coach Nina,Win
35,18-Mar-2026,Wolves,Storm,River Court,Zara,Grade 6,18.0,27.0,3,13,2.0,"$2,041",Coach Omar,Win
36,20-Mar-2026,Tigers,Storm,Sky Hall,Ryan,Grade 7,18.0,9.0,4,6,4.0,"$1,987",Coach Nina,Win
37,22-Mar-2026,Falcons,Knights,Sky Hall,Lily,Grade 7,31.0,25.0,8,4,3.0,"$4,584",Coach Maya,Win
38,24-Mar-2026,Tigers,Comets,Sky Hall,Aarav,Grade 6,29.0,19.0,1,11,4.0,"$2,185",Coach Nina,Win
39,26-Mar-2026,Tigers,Knights,River Court,Ryan,Grade 8,28.0,18.0,11,10,4.0,"$1,421",Coach Nina,Win

In [ ]:
df4.head(5)

In [1]:
df4.head(5)

NameError: name 'df4' is not defined